# Generated by Django 2.2 on 2019-09-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.Ledger')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='ledger',
            field=models.ForeignKey(default=12000, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='records.Ledger'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='records.Account')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='records.Record')),
            ],
        ),
    ]
