# Generated by Django 2.2 on 2019-09-14 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190914_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 14, 8, 25, 13, 935035)),
            preserve_default=False,
        ),
    ]
