# Generated by Django 2.2 on 2019-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
